ex1a : 
	make -f make.ex1a

ex1b :
	make -f make.ex1b

ex2 :
	make -f make.ex2

memtest : 
	make -f make.memtest

ex3 :
	make -f make.ex3

testcycle1 :
	make -f make.testcycle1

testcycle2 :
	make -f make.testcycle2
